#!/usr/bin/env php
<?php

// 应用入口文件
namespace think;

try {
    require __DIR__ . '/vendor/autoload.php';
    
    // 执行命令行
    $app = new App();
    $app->console->run();
    
} catch (\Exception $e) {
    echo $e->getMessage() . PHP_EOL;
    exit(1);
}
